// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace SamuraiApp.Data.CompiledModels
{
    [DbContext(typeof(SamuraiContext))]
    public partial class SamuraiContextModel : RuntimeModel
    {
        static SamuraiContextModel()
        {
            var model = new SamuraiContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static SamuraiContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
