// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace SamuraiApp.Data.CompiledModels
{
    public partial class SamuraiContextModel
    {
        partial void Initialize()
        {
            var quote = QuoteEntityType.Create(this);
            var samurai = SamuraiEntityType.Create(this);

            QuoteEntityType.CreateForeignKey1(quote, samurai);

            QuoteEntityType.CreateAnnotations(quote);
            SamuraiEntityType.CreateAnnotations(samurai);

            AddAnnotation("ProductVersion", "6.0.3");
            AddAnnotation("Relational:MaxIdentifierLength", 128);
            AddAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);
        }
    }
}
